# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
<!DOCTYPE html><html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Community Hub - Policies & Code of Conduct</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Community Hub</h1>
        <nav>
            <ul>
                <li><a href="#code-of-conduct">Code of Conduct</a></li>
                <li><a href="#privacy-policy">Privacy Policy</a></li>
                <li><a href="#terms-of-service">Terms of Service</a></li>
            </ul>
        </nav>
    </header><section id="code-of-conduct">
    <h2>Code of Conduct</h2>
    <p>At Community Hub, we are committed to maintaining a respectful and positive environment. By using our platform, you agree to:</p>
    <ul>
        <li>Respect others and avoid hate speech, harassment, or discrimination.</li>
        <li>Post only lawful and appropriate content.</li>
        <li>Not engage in fraudulent activities.</li>
        <li>Respect intellectual property rights.</li>
        <li>Follow all applicable laws and regulations.</li>
    </ul>
</section>

<section id="privacy-policy">
    <h2>Privacy Policy</h2>
    <p>We value your privacy. Our policies include:</p>
    <ul>
        <li>We collect personal data only for improving our services.</li>
        <li>Your data will not be shared with third parties without consent.</li>
        <li>We use cookies for a better user experience.</li>
        <li>You have the right to request data deletion.</li>
    </ul>
</section>

<section id="terms-of-service">
    <h2>Terms of Service</h2>
    <p>By using Community Hub, you agree to:</p>
    <ul>
        <li>Use the platform legally and ethically.</li>
        <li>Not misuse services or attempt to hack the platform.</li>
        <li>Abide by all payment and content upload policies.</li>
        <li>Understand that violation of these terms may result in account suspension.</li>
    </ul>
</section>

<footer>
    <p>&copy; 2025 Community Hub. All rights reserved.</p>
</footer>

</body>
</html>
